version: "3.9"

services:
  db:
    image: fahimfoysalapurba/mini_ledger_db:latest
    container_name: mini_ledger_db
    ports:
      - "5432:5432"
    networks:
      - ledger-network

  backend:
    image: fahimfoysalapurba/mini_ledger_backend:latest
    container_name: mini_ledger_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - ledger-network

  frontend:
    image: fahimfoysalapurba/mini_ledger_frontend:latest
    container_name: mini_ledger_frontend
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - ledger-network

networks:
  ledger-network:
    driver: bridge







